# Custom Language File for Launcher Customizer

[ejs.app]
title = "호백타운"

[ejs.landing]
mediaGitHubURL = "https://github.com/HXXSTELLA/hxxstella"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaAfreecaTVURL = "#"
mediaChzzkURL = "https://chzzk.naver.com/da504b5309f9b4eee7e9022690e215d1"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/HXXSTELLA/hxxstella"
supportLink = "https://github.com/HXXSTELLA/hxxstella/issues"

[ejs.welcome]
welcomeHeader = "호백타운"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."